version: '3'

services:
  h2:
    build: .
    container_name: 'h2-database'
    hostname: 'h2'
    image: h2docker
    ports:
      - "8181:81"
      - "1521:1521"
    volumes:
      - ./h2-data:/opt/h2/h2-data
